/**
 * Mock response for /journeys/:journey/client-details GET
 */
export const fakeHospitalPreferenceClientDetailsGetResponse = {
  data: {
    page: {
      key: "CLIENT_DETAILS",
      stage: "FACT_FIND",
      route: "/journeys/abcde-11111/client-details",
      conditionals: {
        has_access_to_axa_agency_codes: true
      },
      data: {
        permanent_uk_resident: true,
        covered_with_a_gp_and_access_to_medical_records: false,
        pmi_required_to_fulfil_reqs_or_visa: false,
        tobacco_products_within_last_2_years: false,
        payment_for_participating_in_sport: false,
        last_5_years_heart_condition_or_heart_problem: false,
        last_5_years_stroke: false,
        last_5_years_cancer: false,
        last_5_years_diabetes: false,
        last_5_years_mental_illness: false,
        visited: true
      }
    },
    journey: {
      id: 999,
      slug: "abcde-11111",
      organisation_id: 999,
      network_id: 999,
      user_id: 1005,
      client_id: 999,
      reference: "GZTGE-84845",
      product_type: "PMI",
      current_page: "CURRENT_POLICY_OPTIONS",
      simulation_mode: 1,
      locked: false,
      status: "IN_PROGRESS",
      client: {
        id: 999,
        first_name: "John",
        middle_names: "Apple",
        last_name: "Doe",
        date_of_birth: "1986-12-29",
        gender_at_birth: "male",
        email_address: "john.doe@example.test",
        occupation: "DENTIST",
        created_at: "2021-12-29T12:15:31.000000Z",
        updated_at: "2021-12-30T14:24:45.000000Z",
        deleted_at: null,
        address: {
          id: 6,
          line_one: "42 lytton rd",
          line_two: "",
          city: "oxford",
          county: "Oxfordshire",
          postcode: "OX43NU",
          created_at: "2021-12-29T12:15:32.000000Z",
          updated_at: "2021-12-30T14:24:45.000000Z",
          deleted_at: null
        },
        phone_numbers: [
          {
            id: 1004,
            number: "+447462074657",
            type: "PRIMARY"
          }
        ]
      },
      meta: {
        pages: {
          CONSENT_TO_PERSONAL_INFO: {
            stage: "FACT_FIND",
            order: 0,
            route: "/journeys/abcde-11111/consent"
          },
          CLIENT_DETAILS: {
            stage: "FACT_FIND",
            order: 1,
            route: "/journeys/abcde-11111/client-details"
          },
          APPLICANTS: {
            stage: "FACT_FIND",
            order: 2,
            route: "/journeys/abcde-11111/applicant-details"
          },
          CURRENT_POLICY_DETAILS: {
            stage: "FACT_FIND",
            order: 3,
            route: "/journeys/abcde-11111/current-policy-details"
          }
        }
      },
      created_at: "2021-12-29T12:15:31.000000Z",
      updated_at: "2021-12-30T14:26:00.000000Z",
      deleted_at: null
    }
  }
}

/**
 * Mock response for /hospitals GET
 */
export const fakeHospitalsGetResponse = {
  data: [
    {
      id: 1,
      slug: "the-royal-london-hospital",
      name: "The Royal London Hospital ",
      suite: "",
      address_line_one: "Whitechapel Road",
      address_line_two: "Whitechapel",
      address_line_three: "",
      latitude: 51.52,
      longitude: -0.06000000000000005,
      city: "London",
      county: "London",
      postcode: "E1 1BB",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 2,
      slug: "capio-nightingale-hospital",
      name: "Capio Nightingale Hospital",
      suite: "",
      address_line_one: "11-19 Lisson Grove",
      address_line_two: "Marylebone",
      address_line_three: "",
      latitude: 51.52,
      longitude: -0.17000000000000004,
      city: "",
      county: "London",
      postcode: "NW1 6SH",
      country: "England",
      flags: [""],
      hospital_provider_name: "Capio",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 3,
      slug: "university-college-hospital",
      name: "University College Hospital",
      suite: "Harley Street",
      address_line_one: "15th Floor",
      address_line_two: "University College Hospital",
      address_line_three: "235 Euston Road",
      latitude: 51.52,
      longitude: -0.14,
      city: "",
      county: "London",
      postcode: "NW1 2BU",
      country: "England",
      flags: [""],
      hospital_provider_name: "HCA",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 4,
      slug: "the-whittington-hospital",
      name: "The Whittington Hospital ",
      suite: "",
      address_line_one: "Magdala Avenue",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.57,
      longitude: -0.14,
      city: "London",
      county: "London",
      postcode: "N19 5NF",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 5,
      slug: "abbey-churchill-london-hospital",
      name: "Abbey Churchill London Hospital",
      suite: "Guys & St Thomas ",
      address_line_one: "Great Maze Pond",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.5,
      longitude: -0.08999999999999997,
      city: "London",
      county: "London",
      postcode: "SE1 9RT",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 6,
      slug: "gallions-reach-dental-clinic",
      name: "Gallions Reach Dental Clinic",
      suite: "(day-patient Unit)",
      address_line_one: "Bentham Road",
      address_line_two: "Thamesmead",
      address_line_three: "",
      latitude: 51.51,
      longitude: 0.11,
      city: "London",
      county: "London",
      postcode: "SE28 8BE",
      country: "England",
      flags: [""],
      hospital_provider_name: "Independant",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 7,
      slug: "st-georges-hospital",
      name: "St Georges Hospital ",
      suite: "Atkinson Morley Wing",
      address_line_one: "Blackshaw Road",
      address_line_two: "Tooting",
      address_line_three: "",
      latitude: 51.43,
      longitude: -0.18000000000000005,
      city: "London",
      county: "London",
      postcode: "SW17 0QT",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 8,
      slug: "cygnet-hospital-ealing",
      name: "Cygnet Hospital Ealing",
      suite: "",
      address_line_one: "22 Corfton Road",
      address_line_two: "Ealing",
      address_line_three: "St Thomas Hospital",
      latitude: 51.52,
      longitude: -0.30000000000000004,
      city: "London",
      county: "London",
      postcode: "W5 2HT",
      country: "England",
      flags: [""],
      hospital_provider_name: "Cygnet",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 9,
      slug: "casualty-plus",
      name: "Casualty Plus",
      suite: "",
      address_line_one: "1010 Great West Road",
      address_line_two: "Park Royal",
      address_line_three: "",
      latitude: 51.49,
      longitude: -0.31000000000000005,
      city: "Brentford",
      county: "Middlesex",
      postcode: "TW8 9BA",
      country: "England",
      flags: [""],
      hospital_provider_name: "Independant",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 10,
      slug: "kingston-hospital",
      name: "Kingston Hospital",
      suite: "",
      address_line_one: "Galsworthy Road",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.41,
      longitude: -0.28,
      city: "Kingston-upon-thames",
      county: "Surrey",
      postcode: "KT2 7QB",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 11,
      slug: "harefield-hospital",
      name: "Harefield Hospital ",
      suite: "B Ward",
      address_line_one: "Hill End Road",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.61,
      longitude: -0.48,
      city: "Harefield",
      county: "Middlesex",
      postcode: "UB9 6JH",
      country: "England",
      flags: ["SPECIALIST"],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 12,
      slug: "william-harvey-hospital",
      name: "William Harvey Hospital",
      suite: "",
      address_line_one: "Kennington Road",
      address_line_two: "Willesborough",
      address_line_three: "",
      latitude: 51.14,
      longitude: 0.92,
      city: "Ashford",
      county: "Kent",
      postcode: "TN24 0LZ",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 13,
      slug: "the-royal-buckinghamshire-hospital",
      name: "The Royal Buckinghamshire Hospital",
      suite: "",
      address_line_one: "Buckinghamshire Hospital",
      address_line_two: "Buckingham Rd",
      address_line_three: "Aylesbury",
      latitude: 51.82,
      longitude: -0.8200000000000001,
      city: "",
      county: "Buckinghamshire",
      postcode: "HP19 9AB",
      country: "England",
      flags: [""],
      hospital_provider_name: "Independant",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 14,
      slug: "basildon-university-hospital",
      name: "Basildon University Hospital",
      suite: "Brook Suite",
      address_line_one: "Nethermayne",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.56,
      longitude: 0.45,
      city: "Basildon",
      county: "Essex",
      postcode: "SS16 5NL",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 15,
      slug: "orwell-private-cardiothoracic-unit",
      name: "Orwell Private Cardiothoracic Unit ",
      suite: "",
      address_line_one: "Essex Cardiothoracic Centre",
      address_line_two: "Nethermayne",
      address_line_three: "",
      latitude: 51.56,
      longitude: 0.45,
      city: "Basildon",
      county: "Essex",
      postcode: "SS16 5NL",
      country: "England",
      flags: ["SPECIALIST"],
      hospital_provider_name: "Ramsay",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 16,
      slug: "candover-clinic-basingstoke-north-hampshire-hospital",
      name: "Candover Clinic - Basingstoke & North Hampshire Hospital",
      suite: "Candover Clinic",
      address_line_one: "Aldermaston Road",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.28,
      longitude: -1.1099999999999999,
      city: "Basingstoke",
      county: "Hampshire",
      postcode: "RG24 9NA",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 17,
      slug: "broomfield-hospital",
      name: "Broomfield Hospital",
      suite: "",
      address_line_one: "Court Road",
      address_line_two: "",
      address_line_three: "Broomfield",
      latitude: 51.77,
      longitude: 0.47,
      city: "Chelmsford",
      county: "Essex",
      postcode: "CM1 7ET",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 18,
      slug: "the-chelmsford",
      name: "The Chelmsford ",
      suite: "",
      address_line_one: "Fenton House",
      address_line_two: "85 - 89 New London Road",
      address_line_three: "",
      latitude: 51.73,
      longitude: 0.47,
      city: "Chelmsford",
      county: "Essex",
      postcode: "CM2 0PP",
      country: "England",
      flags: [""],
      hospital_provider_name: "Independant",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 19,
      slug: "colchester-general-hospital",
      name: "Colchester General Hospital",
      suite: "Elmstead Day Ward",
      address_line_one: "Turner Road",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.91,
      longitude: 0.9,
      city: "Colchester",
      county: "Essex",
      postcode: "CO4 5JL",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 20,
      slug: "crawley-hospital",
      name: "Crawley Hospital",
      suite: "",
      address_line_one: "West Green Drive",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.12,
      longitude: -0.19999999999999996,
      city: "Crawley",
      county: "Sussex, West",
      postcode: "RH11 7DH",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 21,
      slug: "eastbourne-district-general-hospital",
      name: "Eastbourne District General Hospital",
      suite: "Michelham Suite",
      address_line_one: "Michelham Private Patients Unit",
      address_line_two: "Kings Drive",
      address_line_three: "",
      latitude: 50.79,
      longitude: 0.27,
      city: "Eastbourne",
      county: "Sussex, East",
      postcode: "BN21 2UD",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 22,
      slug: "the-clock-house-medical-practice",
      name: "The Clock House Medical Practice ",
      suite: "",
      address_line_one: "4 Dorking Road",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.33,
      longitude: -0.27,
      city: "Epsom",
      county: "Surrey",
      postcode: "KT18 7LX",
      country: "England",
      flags: [""],
      hospital_provider_name: "Independant",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 23,
      slug: "royal-surrey-county-hospital",
      name: "Royal Surrey County Hospital",
      suite: " ",
      address_line_one: "Egerton Road",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.24,
      longitude: -0.61,
      city: "Guildford",
      county: "Surrey",
      postcode: "GU2 7XX",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 24,
      slug: "princess-alexandra-hospital",
      name: "Princess Alexandra Hospital",
      suite: "",
      address_line_one: "Hamstel Road",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.77,
      longitude: 0.09,
      city: "Harlow",
      county: "Essex",
      postcode: "CM20 1QX",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 25,
      slug: "the-priory-hospital-brighton-and-hove",
      name: "The Priory Hospital Brighton And Hove",
      suite: "",
      address_line_one: "14-18 New Church Road",
      address_line_two: "",
      address_line_three: "",
      latitude: 50.83,
      longitude: -0.18000000000000005,
      city: "Brighton & Hove",
      county: "Sussex, East",
      postcode: "BN3 4FH",
      country: "England",
      flags: [""],
      hospital_provider_name: "Priory",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 26,
      slug: "the-huntercombe-hospital",
      name: "The Huntercombe Hospital",
      suite: "",
      address_line_one: "Huntercombe Lane South",
      address_line_two: "Taplow",
      address_line_three: "",
      latitude: 51.52,
      longitude: -0.6599999999999999,
      city: "Maidenhead",
      county: "Berkshire",
      postcode: "SL6 0PQ",
      country: "England",
      flags: [""],
      hospital_provider_name: "Huntercombe",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 27,
      slug: "milton-keynes-general-hospital",
      name: "Milton Keynes General Hospital",
      suite: "",
      address_line_one: "Standing Way",
      address_line_two: "Eaglestone",
      address_line_three: "",
      latitude: 52.03,
      longitude: -0.74,
      city: "Milton Keynes",
      county: "Buckinghamshire",
      postcode: "MK6 5LD",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 28,
      slug: "orsett-hospital",
      name: "Orsett Hospital",
      suite: "",
      address_line_one: "Rowley Road",
      address_line_two: "Orsett",
      address_line_three: "",
      latitude: 51.51,
      longitude: 0.37,
      city: "Grays",
      county: "Essex",
      postcode: "RM16 3EU",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 29,
      slug: "royal-berkshire-hospital",
      name: "Royal Berkshire Hospital",
      suite: "",
      address_line_one: "London Road",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.45,
      longitude: -0.96,
      city: "Reading",
      county: "Berkshire",
      postcode: "RG1 5AN",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 30,
      slug: "east-surrey-hospital",
      name: "East Surrey Hospital",
      suite: "",
      address_line_one: "Canada Avenue",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.22,
      longitude: -0.16000000000000003,
      city: "Redhill",
      county: "Surrey",
      postcode: "RH1 5RH",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 31,
      slug: "southend-hospital",
      name: "Southend Hospital",
      suite: "",
      address_line_one: "Prittlewell Chase",
      address_line_two: "",
      address_line_three: "Westcliff-on-sea",
      latitude: 51.55,
      longitude: 0.69,
      city: "Southend",
      county: "Essex",
      postcode: "SS0 0RY",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 32,
      slug: "lynden-hill-clinic",
      name: "Lynden Hill Clinic",
      suite: "",
      address_line_one: "Kiln Green",
      address_line_two: "Nr Twyford",
      address_line_three: "",
      latitude: 51.5,
      longitude: -0.83,
      city: "Twyford",
      county: "Berkshire",
      postcode: "RG10 9XP ",
      country: "England",
      flags: [""],
      hospital_provider_name: "Independant",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 33,
      slug: "royal-hampshire-county-hospital",
      name: "Royal Hampshire County Hospital",
      suite: "",
      address_line_one: "Romsey Road",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.06,
      longitude: -1.33,
      city: "Winchester",
      county: "Hampshire",
      postcode: "SO22 5DG",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 34,
      slug: "life-works-community",
      name: "Life Works Community",
      suite: "",
      address_line_one: "The Grange",
      address_line_two: "High Street",
      address_line_three: "",
      latitude: 51.3,
      longitude: -0.54,
      city: "Old Woking",
      county: "Surrey",
      postcode: "GU22 8LB ",
      country: "England",
      flags: [""],
      hospital_provider_name: "Independant",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 35,
      slug: "salisbury-district-hospital",
      name: "Salisbury District Hospital",
      suite: "Clarendon Suite",
      address_line_one: "Odstock Road",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.04,
      longitude: -1.79,
      city: "Salisbury",
      county: "Wiltshire",
      postcode: "SP2 8BJ",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 36,
      slug: "torbay-hospital",
      name: "Torbay Hospital",
      suite: "",
      address_line_one: "Lawes Bridge",
      address_line_two: "",
      address_line_three: "",
      latitude: 50.48,
      longitude: -3.55,
      city: "Torquay",
      county: "Devon",
      postcode: "TQ2 7AA",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 37,
      slug: "royal-cornwall-hospital",
      name: "Royal Cornwall Hospital",
      suite: "",
      address_line_one: "Treliske",
      address_line_two: "",
      address_line_three: "",
      latitude: 50.27,
      longitude: -5.09,
      city: "Truro",
      county: "Cornwall",
      postcode: "TR1 3LJ",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 38,
      slug: "broadway-lodge",
      name: "Broadway Lodge",
      suite: "",
      address_line_one: "Totterdown Lane",
      address_line_two: "",
      address_line_three: "",
      latitude: 51.32,
      longitude: -2.96,
      city: "Weston-super-mare",
      county: "Somerset",
      postcode: "BS24 9NN ",
      country: "England",
      flags: [""],
      hospital_provider_name: "Independant",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 39,
      slug: "cornwall-house-clinic",
      name: "Cornwall House Clinic",
      suite: "",
      address_line_one: "Sandy Lane",
      address_line_two: "",
      address_line_three: "",
      latitude: 53.02,
      longitude: -2.2199999999999998,
      city: "Newcastle-under-lyme",
      county: "Staffordshire",
      postcode: "ST5 0LZ",
      country: "England",
      flags: [""],
      hospital_provider_name: "InHealth",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 40,
      slug: "george-eliot-hospital",
      name: "George Eliot Hospital",
      suite: "Silas Marner Ward",
      address_line_one: "Lewes House",
      address_line_two: "College Street",
      address_line_three: "",
      latitude: 52.51,
      longitude: -1.48,
      city: "Nuneaton",
      county: "Warwickshire",
      postcode: "CV10 7DJ",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 41,
      slug: "alexandra-hospital",
      name: "Alexandra Hospital",
      suite: "",
      address_line_one: "Woodrow Drive",
      address_line_two: "",
      address_line_three: "",
      latitude: 52.28,
      longitude: -1.91,
      city: "Redditch",
      county: "Worcestershire",
      postcode: "B98 7UB",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:22.000000Z",
      updated_at: "2022-01-14T07:14:22.000000Z",
      deleted_at: null
    },
    {
      id: 42,
      slug: "royal-shrewsbury-hospital",
      name: "Royal Shrewsbury Hospital ",
      suite: "",
      address_line_one: "Mytton Oak Road",
      address_line_two: "",
      address_line_three: "",
      latitude: 52.71,
      longitude: -2.79,
      city: "Shrewsbury",
      county: "Shropshire",
      postcode: "SY3 8XQ",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:23.000000Z",
      updated_at: "2022-01-14T07:14:23.000000Z",
      deleted_at: null
    },
    {
      id: 43,
      slug: "west-suffolk-hospital",
      name: "West Suffolk Hospital",
      suite: "",
      address_line_one: "Hardwick Lane",
      address_line_two: "",
      address_line_three: "",
      latitude: 52.23,
      longitude: 0.71,
      city: "Bury St Edmunds",
      county: "Suffolk",
      postcode: "IP33 2QZ",
      country: "England",
      flags: [""],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:23.000000Z",
      updated_at: "2022-01-14T07:14:23.000000Z",
      deleted_at: null
    },
    {
      id: 44,
      slug: "royal-papworth-hospital",
      name: "Royal Papworth Hospital",
      suite: "Varrier-jones Ward",
      address_line_one: "Papworth Road",
      address_line_two: "Trumpington",
      address_line_three: "",
      latitude: 52.17,
      longitude: 0.14,
      city: "Cambridge",
      county: "Cambridgeshire",
      postcode: "CB2 0AY",
      country: "England",
      flags: ["SPECIALIST"],
      hospital_provider_name: "NHS",
      created_at: "2022-01-14T07:14:23.000000Z",
      updated_at: "2022-01-14T07:14:23.000000Z",
      deleted_at: null
    }
  ]
}
